import { IIncomingCitiesType } from "./cities.type"

const cities:IIncomingCitiesType = {
  "cities": [
    {
      "level": "place2",
      "radius": 6000,
      "centroid": { "latitude": 30.317375, "longitude": 48.334488 },
      "id": 24,
      "name": "آبادان",
      "slug": "abadan",
      "new": false,
      "parent": 902,
      "neighbors": [],
      "second_slug": "abadan",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 3950,
      "centroid": { "latitude": 31.162325, "longitude": 52.646828 },
      "id": 851,
      "name": "آباده",
      "slug": "abadeh",
      "new": false,
      "parent": 898,
      "neighbors": [],
      "second_slug": "abadeh",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 3150,
      "centroid": { "latitude": 32.99174, "longitude": 47.421654 },
      "id": 775,
      "name": "آبدانان",
      "slug": "abdanan",
      "new": false,
      "parent": 888,
      "neighbors": [],
      "second_slug": "abdanan",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 6748,
      "centroid": { "latitude": 35.63648, "longitude": 52.165962 },
      "id": 1709,
      "name": "آبسرد",
      "slug": "absard",
      "new": false,
      "parent": 904,
      "neighbors": [],
      "second_slug": "absard",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 2103,
      "centroid": { "latitude": 35.76871, "longitude": 51.9612 },
      "id": 1715,
      "name": "آبعلی",
      "slug": "abali",
      "new": false,
      "parent": 904,
      "neighbors": [],
      "second_slug": "abali",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 3000,
      "centroid": { "latitude": 36.046852, "longitude": 50.535755 },
      "id": 869,
      "name": "آبیک",
      "slug": "abyek",
      "new": false,
      "parent": 878,
      "neighbors": [],
      "second_slug": "abyek",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 4800,
      "centroid": { "latitude": 37.753826, "longitude": 45.982502 },
      "id": 853,
      "name": "آذرشهر",
      "slug": "azarshahr",
      "new": false,
      "parent": 891,
      "neighbors": [],
      "second_slug": "azarshahr",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 3001,
      "centroid": { "latitude": 34.061275, "longitude": 51.47581 },
      "id": 1737,
      "name": "آران و بیدگل",
      "slug": "aran-va-bidgol",
      "new": false,
      "parent": 890,
      "neighbors": [],
      "second_slug": "aran-va-bidgol",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 2563,
      "centroid": { "latitude": 37.08735, "longitude": 55.177788 },
      "id": 1691,
      "name": "آزادشهر",
      "slug": "azadshahr-golestan",
      "new": false,
      "parent": 897,
      "neighbors": [],
      "second_slug": "azadshahr-golestan",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 1044,
      "centroid": { "latitude": 36.03806, "longitude": 51.19354 },
      "id": 1722,
      "name": "آسارا",
      "slug": "asara",
      "new": false,
      "parent": 895,
      "neighbors": [],
      "second_slug": "asara",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 4800,
      "centroid": { "latitude": 38.427353, "longitude": 48.861893 },
      "id": 824,
      "name": "آستارا",
      "slug": "astara",
      "new": false,
      "parent": 889,
      "neighbors": [],
      "second_slug": "astara",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 2060,
      "centroid": { "latitude": 37.265373, "longitude": 49.938736 },
      "id": 825,
      "name": "آستانه اشرفیه",
      "slug": "astaneh-ashrafiyeh",
      "new": false,
      "parent": 889,
      "neighbors": [],
      "second_slug": "astaneh-ashrafiyeh",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 1680,
      "centroid": { "latitude": 37.558823, "longitude": 56.92376 },
      "id": 793,
      "name": "آشخانه",
      "slug": "ashkhaneh",
      "new": false,
      "parent": 896,
      "neighbors": [],
      "second_slug": "ashkhaneh",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 1645,
      "centroid": { "latitude": 37.01281, "longitude": 54.45628 },
      "id": 748,
      "name": "آق قلا",
      "slug": "aq-qala",
      "new": true,
      "parent": 897,
      "neighbors": [],
      "second_slug": "aq-qala",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 5000,
      "centroid": { "latitude": 36.46499, "longitude": 52.356953 },
      "id": 663,
      "name": "آمل",
      "slug": "amol",
      "new": false,
      "parent": 893,
      "neighbors": [],
      "second_slug": "amol",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 3259,
      "centroid": { "latitude": 32.570827, "longitude": 51.57263 },
      "id": 1723,
      "name": "ابریشم",
      "slug": "abrisham-isfahan",
      "new": false,
      "parent": 890,
      "neighbors": [],
      "second_slug": "abrisham-isfahan",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 5000,
      "centroid": { "latitude": 36.14811, "longitude": 49.23506 },
      "id": 802,
      "name": "ابهر",
      "slug": "abhar",
      "new": false,
      "parent": 879,
      "neighbors": [],
      "second_slug": "abhar",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 15000,
      "centroid": { "latitude": 34.08251, "longitude": 49.70063 },
      "id": 15,
      "name": "اراک",
      "slug": "arak",
      "new": false,
      "parent": 901,
      "neighbors": [],
      "second_slug": "arak",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 1080,
      "centroid": { "latitude": 35.81531, "longitude": 52.512783 },
      "id": 1714,
      "name": "ارجمند",
      "slug": "arjmand",
      "new": false,
      "parent": 904,
      "neighbors": [],
      "second_slug": "arjmand",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 15000,
      "centroid": { "latitude": 38.2647, "longitude": 48.318043 },
      "id": 17,
      "name": "اردبیل",
      "slug": "ardabil",
      "new": false,
      "parent": 906,
      "neighbors": [],
      "second_slug": "ardabil",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 3200,
      "centroid": { "latitude": 32.30908, "longitude": 54.014355 },
      "id": 846,
      "name": "اردکان",
      "slug": "ardakan",
      "new": false,
      "parent": 886,
      "neighbors": [],
      "second_slug": "ardakan",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 15000,
      "centroid": { "latitude": 37.55548, "longitude": 45.056343 },
      "id": 10,
      "name": "ارومیه",
      "slug": "urmia",
      "new": false,
      "parent": 881,
      "neighbors": [],
      "second_slug": "urmia",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 5600,
      "centroid": { "latitude": 33.451534, "longitude": 49.453358 },
      "id": 870,
      "name": "ازنا",
      "slug": "azna",
      "new": false,
      "parent": 884,
      "neighbors": [],
      "second_slug": "azna",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 2900,
      "centroid": { "latitude": 34.78158, "longitude": 48.120094 },
      "id": 842,
      "name": "اسدآباد",
      "slug": "asadabad",
      "new": false,
      "parent": 899,
      "neighbors": [],
      "second_slug": "asadabad",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 4690,
      "centroid": { "latitude": 37.063538, "longitude": 57.50791 },
      "id": 794,
      "name": "اسفراین",
      "slug": "esfarayen",
      "new": false,
      "parent": 896,
      "neighbors": [],
      "second_slug": "esfarāyen",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 4900,
      "centroid": { "latitude": 34.110306, "longitude": 46.526028 },
      "id": 819,
      "name": "اسلام‌‌آباد غرب",
      "slug": "eslamabad-gharb",
      "new": false,
      "parent": 905,
      "neighbors": [],
      "second_slug": "eslamabad-gharb",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 5000,
      "centroid": { "latitude": 35.538013, "longitude": 51.236763 },
      "id": 29,
      "name": "اسلام‌شهر",
      "slug": "eslamshahr",
      "new": false,
      "parent": 904,
      "neighbors": [],
      "second_slug": "eslamshahr",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 2639,
      "centroid": { "latitude": 35.72189, "longitude": 50.36788 },
      "id": 1721,
      "name": "اشتهارد",
      "slug": "eshtehard",
      "new": false,
      "parent": 895,
      "neighbors": [],
      "second_slug": "eshtehard",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 1835,
      "centroid": { "latitude": 37.037086, "longitude": 45.09847 },
      "id": 859,
      "name": "اشنویه",
      "slug": "oshnavieh",
      "new": false,
      "parent": 881,
      "neighbors": [],
      "second_slug": "oshnavieh",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 20000,
      "centroid": { "latitude": 32.657566, "longitude": 51.672817 },
      "id": 4,
      "name": "اصفهان",
      "slug": "isfahan",
      "new": false,
      "parent": 890,
      "neighbors": [],
      "second_slug": "isfahan",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 6710,
      "centroid": { "latitude": 30.897594, "longitude": 52.69092 },
      "id": 1728,
      "name": "اقلید",
      "slug": "eqlid",
      "new": false,
      "parent": 898,
      "neighbors": [],
      "second_slug": "eqlid",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 1880,
      "centroid": { "latitude": 36.186848, "longitude": 50.058636 },
      "id": 872,
      "name": "الوند",
      "slug": "alvand",
      "new": false,
      "parent": 878,
      "neighbors": [],
      "second_slug": "alvand",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 4020,
      "centroid": { "latitude": 33.39677, "longitude": 49.698986 },
      "id": 830,
      "name": "الیگودرز",
      "slug": "aligudarz",
      "new": false,
      "parent": 884,
      "neighbors": [],
      "second_slug": "aligudarz",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 1780,
      "centroid": { "latitude": 37.09569, "longitude": 50.18479 },
      "id": 1688,
      "name": "املش",
      "slug": "amlash",
      "new": false,
      "parent": 889,
      "neighbors": [],
      "second_slug": "amlash",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 1490,
      "centroid": { "latitude": 36.598938, "longitude": 52.665886 },
      "id": 1703,
      "name": "امیرکلا",
      "slug": "amirkala",
      "new": false,
      "parent": 893,
      "neighbors": [],
      "second_slug": "amirkala",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 5430,
      "centroid": { "latitude": 32.461273, "longitude": 48.34196 },
      "id": 796,
      "name": "اندیمشک",
      "slug": "andimeshk",
      "new": false,
      "parent": 902,
      "neighbors": [],
      "second_slug": "andimeshk",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 4000,
      "centroid": { "latitude": 38.479786, "longitude": 47.071163 },
      "id": 759,
      "name": "اهر",
      "slug": "ahar",
      "new": false,
      "parent": 891,
      "neighbors": [],
      "second_slug": "ahar",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 15000,
      "centroid": { "latitude": 31.362139, "longitude": 48.65707 },
      "id": 7,
      "name": "اهواز",
      "slug": "ahvaz",
      "new": false,
      "parent": 902,
      "neighbors": [],
      "second_slug": "ahvaz",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 3200,
      "centroid": { "latitude": 31.826155, "longitude": 49.866783 },
      "id": 797,
      "name": "ایذه",
      "slug": "izeh",
      "new": false,
      "parent": 902,
      "neighbors": [],
      "second_slug": "izeh",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 7180,
      "centroid": { "latitude": 27.215057, "longitude": 60.68575 },
      "id": 807,
      "name": "ایرانشهر",
      "slug": "Iranshahr",
      "new": false,
      "parent": 883,
      "neighbors": [],
      "second_slug": "iranshahr",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 773,
      "centroid": { "latitude": 36.594006, "longitude": 52.127956 },
      "id": 1701,
      "name": "ایزدشهر",
      "slug": "izadshahr",
      "new": false,
      "parent": 893,
      "neighbors": [],
      "second_slug": "izadshahr",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 10000,
      "centroid": { "latitude": 33.63669, "longitude": 46.414482 },
      "id": 32,
      "name": "ایلام",
      "slug": "ilam",
      "new": false,
      "parent": 888,
      "neighbors": [],
      "second_slug": "ilam",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 2480,
      "centroid": { "latitude": 33.828037, "longitude": 46.308067 },
      "id": 776,
      "name": "ایوان",
      "slug": "eyvan",
      "new": false,
      "parent": 888,
      "neighbors": [],
      "second_slug": "eyvan",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 5000,
      "centroid": { "latitude": 36.540527, "longitude": 52.67958 },
      "id": 664,
      "name": "بابل",
      "slug": "babol",
      "new": false,
      "parent": 893,
      "neighbors": [],
      "second_slug": "babol",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 7000,
      "centroid": { "latitude": 36.70077, "longitude": 52.659985 },
      "id": 710,
      "name": "بابلسر",
      "slug": "babolsar",
      "new": false,
      "parent": 893,
      "neighbors": [],
      "second_slug": "babolsar",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 1279,
      "centroid": { "latitude": 35.53221, "longitude": 51.40576 },
      "id": 1707,
      "name": "باقرشهر",
      "slug": "baghershahr",
      "new": false,
      "parent": 904,
      "neighbors": [],
      "second_slug": "baghershahr",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 4000,
      "centroid": { "latitude": 35.994667, "longitude": 45.887016 },
      "id": 662,
      "name": "بانه",
      "slug": "baneh",
      "new": false,
      "parent": 885,
      "neighbors": [],
      "second_slug": "baneh",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 6000,
      "centroid": { "latitude": 37.479904, "longitude": 57.324593 },
      "id": 39,
      "name": "بجنورد",
      "slug": "bojnurd",
      "new": false,
      "parent": 896,
      "neighbors": [],
      "second_slug": "bojnurd",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 4090,
      "centroid": { "latitude": 29.268408, "longitude": 51.21755 },
      "id": 778,
      "name": "برازجان",
      "slug": "borazjan",
      "new": false,
      "parent": 900,
      "neighbors": [],
      "second_slug": "borazjan",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 3364,
      "centroid": { "latitude": 35.25958, "longitude": 57.974037 },
      "id": 1735,
      "name": "بردسکن",
      "slug": "bardaskan",
      "new": false,
      "parent": 880,
      "neighbors": [],
      "second_slug": "bardaskan",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 10000,
      "centroid": { "latitude": 33.89676, "longitude": 48.757004 },
      "id": 26,
      "name": "بروجرد",
      "slug": "borujerd",
      "new": false,
      "parent": 884,
      "neighbors": [],
      "second_slug": "borujerd",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 6460,
      "centroid": { "latitude": 31.973633, "longitude": 51.3008 },
      "id": 785,
      "name": "بروجن",
      "slug": "boroujen",
      "new": false,
      "parent": 903,
      "neighbors": [],
      "second_slug": "boroujen",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 6100,
      "centroid": { "latitude": 29.102898, "longitude": 58.3472 },
      "id": 815,
      "name": "بم",
      "slug": "bam",
      "new": false,
      "parent": 877,
      "neighbors": [],
      "second_slug": "bam",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 8000,
      "centroid": { "latitude": 37.342693, "longitude": 46.059204 },
      "id": 760,
      "name": "بناب",
      "slug": "bonab",
      "new": false,
      "parent": 891,
      "neighbors": [],
      "second_slug": "bonab",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 6435,
      "centroid": { "latitude": 30.46572, "longitude": 49.079952 },
      "id": 798,
      "name": "بندر امام خمینی",
      "slug": "bandar-Imam-khomeini",
      "new": false,
      "parent": 902,
      "neighbors": [],
      "second_slug": "bandar-imam-khomeini",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 20000,
      "centroid": { "latitude": 37.469254, "longitude": 49.477436 },
      "id": 708,
      "name": "بندر انزلی",
      "slug": "bandar-anzali",
      "new": false,
      "parent": 889,
      "neighbors": [],
      "second_slug": "bandar-anzali",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 3470,
      "centroid": { "latitude": 36.90634, "longitude": 54.07229 },
      "id": 751,
      "name": "بندر ترکمن",
      "slug": "bandar-torkaman",
      "new": true,
      "parent": 897,
      "neighbors": [],
      "second_slug": "bandar-torkaman",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 15000,
      "centroid": { "latitude": 27.188486, "longitude": 56.22356 },
      "id": 18,
      "name": "بندرعباس",
      "slug": "bandar-abbas",
      "new": false,
      "parent": 894,
      "neighbors": [],
      "second_slug": "bandar-abbas",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 6000,
      "centroid": { "latitude": 27.834257, "longitude": 52.073414 },
      "id": 779,
      "name": "بندر کنگان",
      "slug": "bandar-kangan",
      "new": false,
      "parent": 900,
      "neighbors": [],
      "second_slug": "bandar-kangan",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 5420,
      "centroid": { "latitude": 29.58303, "longitude": 50.514767 },
      "id": 780,
      "name": "بندر گناوه",
      "slug": "bandar-ganaveh",
      "new": false,
      "parent": 900,
      "neighbors": [],
      "second_slug": "bandar-ganaveh",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 5000,
      "centroid": { "latitude": 30.559885, "longitude": 49.179203 },
      "id": 37,
      "name": "بندر ماهشهر",
      "slug": "mahshahr",
      "new": false,
      "parent": 902,
      "neighbors": [],
      "second_slug": "bandar-mahshahr",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 10000,
      "centroid": { "latitude": 28.894758, "longitude": 50.90273 },
      "id": 25,
      "name": "بوشهر",
      "slug": "bushehr",
      "new": false,
      "parent": 900,
      "neighbors": [],
      "second_slug": "bushehr",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 5250,
      "centroid": { "latitude": 36.521793, "longitude": 46.20791 },
      "id": 765,
      "name": "بوکان",
      "slug": "bukan",
      "new": false,
      "parent": 881,
      "neighbors": [],
      "second_slug": "bukan",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 3000,
      "centroid": { "latitude": 30.593267, "longitude": 50.238525 },
      "id": 314,
      "name": "بهبهان",
      "slug": "behbahan",
      "new": false,
      "parent": 902,
      "neighbors": [],
      "second_slug": "behbahan",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 4630,
      "centroid": { "latitude": 36.692665, "longitude": 53.538948 },
      "id": 832,
      "name": "بهشهر",
      "slug": "behshahr",
      "new": false,
      "parent": 893,
      "neighbors": [],
      "second_slug": "behshahr",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 2500,
      "centroid": { "latitude": 35.87472, "longitude": 47.599842 },
      "id": 868,
      "name": "بیجار",
      "slug": "bijar",
      "new": false,
      "parent": 885,
      "neighbors": [],
      "second_slug": "bijar",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 10000,
      "centroid": { "latitude": 32.87195, "longitude": 59.240166 },
      "id": 34,
      "name": "بیرجند",
      "slug": "birjand",
      "new": false,
      "parent": 876,
      "neighbors": [],
      "second_slug": "birjand",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 5560,
      "centroid": { "latitude": 39.627834, "longitude": 47.90148 },
      "id": 771,
      "name": "پارس‌آباد",
      "slug": "parsabad",
      "new": false,
      "parent": 906,
      "neighbors": [],
      "second_slug": "parsabad",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 4630,
      "centroid": { "latitude": 36.111862, "longitude": 53.058716 },
      "id": 1702,
      "name": "پل سفید",
      "slug": "polsefid",
      "new": false,
      "parent": 893,
      "neighbors": [],
      "second_slug": "polsefid",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 2700,
      "centroid": { "latitude": 36.69534, "longitude": 45.144825 },
      "id": 766,
      "name": "پیرانشهر",
      "slug": "piranshahr",
      "new": false,
      "parent": 881,
      "neighbors": [],
      "second_slug": "piranshahr",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 3570,
      "centroid": { "latitude": 35.30681, "longitude": 51.728138 },
      "id": 781,
      "name": "پیشوا",
      "slug": "pishva",
      "new": false,
      "parent": 904,
      "neighbors": [],
      "second_slug": "pishva",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 5000,
      "centroid": { "latitude": 36.072216, "longitude": 49.69402 },
      "id": 811,
      "name": "تاکستان",
      "slug": "takestan",
      "new": false,
      "parent": 878,
      "neighbors": [],
      "second_slug": "takestan",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 5350,
      "centroid": { "latitude": 37.802914, "longitude": 48.906734 },
      "id": 829,
      "name": "تالش",
      "slug": "talesh",
      "new": false,
      "parent": 889,
      "neighbors": [],
      "second_slug": "talesh",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 3849,
      "centroid": { "latitude": 34.743862, "longitude": 60.778206 },
      "id": 1729,
      "name": "تایباد",
      "slug": "taybad",
      "new": false,
      "parent": 880,
      "neighbors": [],
      "second_slug": "taybad",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 15000,
      "centroid": { "latitude": 38.072517, "longitude": 46.29488 },
      "id": 5,
      "name": "تبریز",
      "slug": "tabriz",
      "new": false,
      "parent": 891,
      "neighbors": [],
      "second_slug": "tabriz",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 5250,
      "centroid": { "latitude": 35.23555, "longitude": 60.628197 },
      "id": 791,
      "name": "تربت جام",
      "slug": "torbat-jam",
      "new": false,
      "parent": 880,
      "neighbors": [],
      "second_slug": "torbat-jam",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 6085,
      "centroid": { "latitude": 36.812695, "longitude": 50.875507 },
      "id": 833,
      "name": "تنکابن",
      "slug": "tonekabon",
      "new": false,
      "parent": 893,
      "neighbors": [],
      "second_slug": "tonekabon",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 1033,
      "centroid": { "latitude": 35.891724, "longitude": 50.616695 },
      "id": 1739,
      "name": "تنکمان",
      "slug": "tankaman",
      "new": false,
      "parent": 895,
      "neighbors": [],
      "second_slug": "tankaman",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 3450,
      "centroid": { "latitude": 34.54873, "longitude": 48.451065 },
      "id": 866,
      "name": "تویسرکان",
      "slug": "tuyserkan",
      "new": false,
      "parent": 899,
      "neighbors": [],
      "second_slug": "tuyserkan",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 25000,
      "centroid": { "latitude": 35.717358, "longitude": 51.375076 },
      "id": 1,
      "name": "تهران",
      "slug": "tehran",
      "new": false,
      "parent": 904,
      "neighbors": [],
      "second_slug": "tehran",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 1103,
      "centroid": { "latitude": 35.21277, "longitude": 51.671837 },
      "id": 1718,
      "name": "جوادآباد",
      "slug": "javadabad",
      "new": false,
      "parent": 904,
      "neighbors": [],
      "second_slug": "javadabad",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 1740,
      "centroid": { "latitude": 34.805958, "longitude": 46.49457 },
      "id": 820,
      "name": "جوانرود",
      "slug": "javanrud",
      "new": false,
      "parent": 905,
      "neighbors": [],
      "second_slug": "javanrud",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 2900,
      "centroid": { "latitude": 36.642315, "longitude": 52.90417 },
      "id": 834,
      "name": "جویبار",
      "slug": "juybar",
      "new": false,
      "parent": 893,
      "neighbors": [],
      "second_slug": "juybar",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 8980,
      "centroid": { "latitude": 28.518656, "longitude": 53.582703 },
      "id": 808,
      "name": "جهرم",
      "slug": "jahrom",
      "new": false,
      "parent": 898,
      "neighbors": [],
      "second_slug": "jahrom",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 9660,
      "centroid": { "latitude": 28.686445, "longitude": 57.72085 },
      "id": 816,
      "name": "جیرفت",
      "slug": "jiroft",
      "new": false,
      "parent": 877,
      "neighbors": [],
      "second_slug": "jiroft",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 1960,
      "centroid": { "latitude": 36.97469, "longitude": 50.56205 },
      "id": 864,
      "name": "چابکسر",
      "slug": "chaboksar",
      "new": false,
      "parent": 889,
      "neighbors": [],
      "second_slug": "chaboksar",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 64900,
      "centroid": { "latitude": 25.303268, "longitude": 60.646236 },
      "id": 747,
      "name": "چابهار",
      "slug": "chabahar",
      "new": true,
      "parent": 883,
      "neighbors": [],
      "second_slug": "chabahar",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 2285,
      "centroid": { "latitude": 37.229443, "longitude": 50.253887 },
      "id": 1686,
      "name": "چاف و چمخاله",
      "slug": "chaf-chamkhale",
      "new": false,
      "parent": 889,
      "neighbors": [],
      "second_slug": "chaf-chamkhale",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 3260,
      "centroid": { "latitude": 36.658092, "longitude": 51.420853 },
      "id": 835,
      "name": "چالوس",
      "slug": "chalus",
      "new": false,
      "parent": 893,
      "neighbors": [],
      "second_slug": "chalus",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 983,
      "centroid": { "latitude": 36.48342, "longitude": 52.12138 },
      "id": 1694,
      "name": "چمستان",
      "slug": "chamestan",
      "new": false,
      "parent": 893,
      "neighbors": [],
      "second_slug": "chamestan",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 2552,
      "centroid": { "latitude": 36.642967, "longitude": 59.119015 },
      "id": 1732,
      "name": "چناران",
      "slug": "chenaran",
      "new": false,
      "parent": 880,
      "neighbors": [],
      "second_slug": "chenaran",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 1038,
      "centroid": { "latitude": 35.839554, "longitude": 50.850216 },
      "id": 1740,
      "name": "چهارباغ",
      "slug": "charbagh-alborz",
      "new": false,
      "parent": 895,
      "neighbors": [],
      "second_slug": "charbagh-alborz",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 4290,
      "centroid": { "latitude": 35.598732, "longitude": 51.314415 },
      "id": 782,
      "name": "چهاردانگه",
      "slug": "chahar-dangeh",
      "new": false,
      "parent": 904,
      "neighbors": [],
      "second_slug": "chahar-dangeh",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 2110,
      "centroid": { "latitude": 31.828205, "longitude": 54.395912 },
      "id": 871,
      "name": "حمیدیا",
      "slug": "hamidia",
      "new": false,
      "parent": 886,
      "neighbors": [],
      "second_slug": "hamidia",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 10000,
      "centroid": { "latitude": 33.476715, "longitude": 48.348457 },
      "id": 27,
      "name": "خرم‌آباد",
      "slug": "khorramabad",
      "new": false,
      "parent": 884,
      "neighbors": [],
      "second_slug": "khorramabad",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 3440,
      "centroid": { "latitude": 36.20894, "longitude": 49.196438 },
      "id": 803,
      "name": "خرمدره",
      "slug": "khorramdarreh",
      "new": false,
      "parent": 879,
      "neighbors": [],
      "second_slug": "khorramdarreh",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 8310,
      "centroid": { "latitude": 30.42547, "longitude": 48.187717 },
      "id": 799,
      "name": "خرمشهر",
      "slug": "khorramshahr",
      "new": false,
      "parent": 902,
      "neighbors": [],
      "second_slug": "khorramshahr",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 1890,
      "centroid": { "latitude": 37.37302, "longitude": 49.75766 },
      "id": 1689,
      "name": "خشکبیجار",
      "slug": "khoshkbijar",
      "new": false,
      "parent": 889,
      "neighbors": [],
      "second_slug": "khoshkbijar",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 5400,
      "centroid": { "latitude": 37.619774, "longitude": 48.53143 },
      "id": 772,
      "name": "خلخال",
      "slug": "khalkhal",
      "new": false,
      "parent": 906,
      "neighbors": [],
      "second_slug": "khalkhal",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 5500,
      "centroid": { "latitude": 33.63772, "longitude": 50.069836 },
      "id": 839,
      "name": "خمین",
      "slug": "khomein",
      "new": false,
      "parent": 901,
      "neighbors": [],
      "second_slug": "khomein",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 3737,
      "centroid": { "latitude": 34.573875, "longitude": 60.14224 },
      "id": 1736,
      "name": "خواف",
      "slug": "khaf",
      "new": false,
      "parent": 880,
      "neighbors": [],
      "second_slug": "khaf",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 7191,
      "centroid": { "latitude": 33.26682, "longitude": 50.3171 },
      "id": 1727,
      "name": "خوانسار",
      "slug": "khansar",
      "new": false,
      "parent": 890,
      "neighbors": [],
      "second_slug": "khansar",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 4400,
      "centroid": { "latitude": 38.549664, "longitude": 44.952152 },
      "id": 767,
      "name": "خوی",
      "slug": "khoy",
      "new": false,
      "parent": 881,
      "neighbors": [],
      "second_slug": "khoy",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 4670,
      "centroid": { "latitude": 28.751759, "longitude": 54.547695 },
      "id": 809,
      "name": "داراب",
      "slug": "darab",
      "new": false,
      "parent": 898,
      "neighbors": [],
      "second_slug": "darab",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 2430,
      "centroid": { "latitude": 32.985775, "longitude": 50.409534 },
      "id": 1724,
      "name": "داران",
      "slug": "daran",
      "new": false,
      "parent": 890,
      "neighbors": [],
      "second_slug": "daran",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 3800,
      "centroid": { "latitude": 36.16486, "longitude": 54.342262 },
      "id": 805,
      "name": "دامغان",
      "slug": "damghan",
      "new": false,
      "parent": 882,
      "neighbors": [],
      "second_slug": "damghan",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 8000,
      "centroid": { "latitude": 32.396294, "longitude": 48.395267 },
      "id": 23,
      "name": "دزفول",
      "slug": "dezful",
      "new": false,
      "parent": 902,
      "neighbors": [],
      "second_slug": "dezful",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 5290,
      "centroid": { "latitude": 35.703564, "longitude": 52.048042 },
      "id": 783,
      "name": "دماوند",
      "slug": "damavand",
      "new": false,
      "parent": 904,
      "neighbors": [],
      "second_slug": "damavand",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 3270,
      "centroid": { "latitude": 33.494804, "longitude": 49.062233 },
      "id": 752,
      "name": "دورود",
      "slug": "dorud",
      "new": true,
      "parent": 884,
      "neighbors": [],
      "second_slug": "dorud",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 8090,
      "centroid": { "latitude": 30.357033, "longitude": 50.796616 },
      "id": 874,
      "name": "دوگنبدان",
      "slug": "dogonbadan",
      "new": false,
      "parent": 887,
      "neighbors": [],
      "second_slug": "dogonbadan",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 6040,
      "centroid": { "latitude": 30.7888, "longitude": 50.57921 },
      "id": 822,
      "name": "دهدشت",
      "slug": "dehdasht",
      "new": false,
      "parent": 887,
      "neighbors": [],
      "second_slug": "dehdasht",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 2650,
      "centroid": { "latitude": 32.691166, "longitude": 47.269024 },
      "id": 777,
      "name": "دهلران",
      "slug": "dehloran",
      "new": false,
      "parent": 888,
      "neighbors": [],
      "second_slug": "dehloran",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 5560,
      "centroid": { "latitude": 36.924072, "longitude": 50.642384 },
      "id": 745,
      "name": "رامسر",
      "slug": "ramsar",
      "new": true,
      "parent": 893,
      "neighbors": [],
      "second_slug": "ramsar",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 3630,
      "centroid": { "latitude": 31.27535, "longitude": 49.610558 },
      "id": 800,
      "name": "رامهرمز",
      "slug": "ramhormoz",
      "new": false,
      "parent": 902,
      "neighbors": [],
      "second_slug": "ramhormoz",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 20000,
      "centroid": { "latitude": 37.261196, "longitude": 49.593647 },
      "id": 12,
      "name": "رشت",
      "slug": "rasht",
      "new": false,
      "parent": 889,
      "neighbors": [],
      "second_slug": "rasht",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 3640,
      "centroid": { "latitude": 37.56, "longitude": 49.15 },
      "id": 1684,
      "name": "رضوانشهر",
      "slug": "rezvanshahr",
      "new": false,
      "parent": 889,
      "neighbors": [],
      "second_slug": "rezvanshahr",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 11630,
      "centroid": { "latitude": 30.361021, "longitude": 55.991436 },
      "id": 817,
      "name": "رفسنجان",
      "slug": "rafsanjan",
      "new": false,
      "parent": 877,
      "neighbors": [],
      "second_slug": "rafsanjan",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 4270,
      "centroid": { "latitude": 37.137886, "longitude": 50.299564 },
      "id": 826,
      "name": "رودسر",
      "slug": "rudsar",
      "new": false,
      "parent": 889,
      "neighbors": [],
      "second_slug": "rudsar",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 1256,
      "centroid": { "latitude": 36.567326, "longitude": 51.96853 },
      "id": 1698,
      "name": "رویان",
      "slug": "royan",
      "new": false,
      "parent": 893,
      "neighbors": [],
      "second_slug": "royan",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 6000,
      "centroid": { "latitude": 31.040257, "longitude": 61.500496 },
      "id": 706,
      "name": "زابل",
      "slug": "zabol",
      "new": true,
      "parent": 883,
      "neighbors": [],
      "second_slug": "zabol",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 18000,
      "centroid": { "latitude": 29.470049, "longitude": 60.86604 },
      "id": 11,
      "name": "زاهدان",
      "slug": "zahedan",
      "new": false,
      "parent": 883,
      "neighbors": [],
      "second_slug": "zahedan",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 5450,
      "centroid": { "latitude": 30.810305, "longitude": 56.578514 },
      "id": 867,
      "name": "زرند",
      "slug": "zarand",
      "new": false,
      "parent": 877,
      "neighbors": [],
      "second_slug": "zarand",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 10000,
      "centroid": { "latitude": 36.67692, "longitude": 48.502293 },
      "id": 20,
      "name": "زنجان",
      "slug": "zanjan",
      "new": false,
      "parent": 879,
      "neighbors": [],
      "second_slug": "zanjan",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 1410,
      "centroid": { "latitude": 37.416744, "longitude": 49.87 },
      "id": 1683,
      "name": "زیباکنار",
      "slug": "zibakenar",
      "new": false,
      "parent": 889,
      "neighbors": [],
      "second_slug": "zibakenar",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 5000,
      "centroid": { "latitude": 36.561245, "longitude": 53.062508 },
      "id": 22,
      "name": "ساری",
      "slug": "sari",
      "new": false,
      "parent": 893,
      "neighbors": [],
      "second_slug": "sari",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 5000,
      "centroid": { "latitude": 35.025944, "longitude": 50.364273 },
      "id": 671,
      "name": "ساوه",
      "slug": "saveh",
      "new": false,
      "parent": 901,
      "neighbors": [],
      "second_slug": "saveh",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 9000,
      "centroid": { "latitude": 36.21749, "longitude": 57.65594 },
      "id": 316,
      "name": "سبزوار",
      "slug": "sabzevar",
      "new": false,
      "parent": 880,
      "neighbors": [],
      "second_slug": "sabzevar",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 2500,
      "centroid": { "latitude": 37.940243, "longitude": 47.532413 },
      "id": 852,
      "name": "سراب",
      "slug": "sarab",
      "new": false,
      "parent": 891,
      "neighbors": [],
      "second_slug": "sarab",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 8300,
      "centroid": { "latitude": 27.346884, "longitude": 62.35219 },
      "id": 865,
      "name": "سراوان",
      "slug": "saravan",
      "new": false,
      "parent": 883,
      "neighbors": [],
      "second_slug": "saravan",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 2500,
      "centroid": { "latitude": 34.45784, "longitude": 45.859917 },
      "id": 854,
      "name": "سرپل ذهاب",
      "slug": "sarpol-zahab",
      "new": false,
      "parent": 905,
      "neighbors": [],
      "second_slug": "sarpol-zahab",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 1544,
      "centroid": { "latitude": 36.479664, "longitude": 52.120438 },
      "id": 1700,
      "name": "سرخرود",
      "slug": "sorkhrood",
      "new": false,
      "parent": 893,
      "neighbors": [],
      "second_slug": "sorkhrood",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 2700,
      "centroid": { "latitude": 36.15822, "longitude": 45.47813 },
      "id": 857,
      "name": "سردشت",
      "slug": "sardasht",
      "new": false,
      "parent": 881,
      "neighbors": [],
      "second_slug": "sardasht",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 3450,
      "centroid": { "latitude": 36.23966, "longitude": 46.27641 },
      "id": 812,
      "name": "سقز",
      "slug": "saqqez",
      "new": false,
      "parent": 885,
      "neighbors": [],
      "second_slug": "saqqez",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 3320,
      "centroid": { "latitude": 38.199913, "longitude": 44.768105 },
      "id": 768,
      "name": "سلماس",
      "slug": "salmas",
      "new": false,
      "parent": 881,
      "neighbors": [],
      "second_slug": "salmas",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 1587,
      "centroid": { "latitude": 36.6947, "longitude": 51.1955 },
      "id": 1699,
      "name": "سلمان‌شهر",
      "slug": "salman-shahr",
      "new": false,
      "parent": 893,
      "neighbors": [],
      "second_slug": "salman-shahr",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 5000,
      "centroid": { "latitude": 35.57904, "longitude": 53.387352 },
      "id": 35,
      "name": "سمنان",
      "slug": "semnan",
      "new": false,
      "parent": 882,
      "neighbors": [],
      "second_slug": "semnan",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 5696,
      "centroid": { "latitude": 31.396917, "longitude": 51.575382 },
      "id": 1725,
      "name": "سمیرم",
      "slug": "semirom",
      "new": false,
      "parent": 890,
      "neighbors": [],
      "second_slug": "semirom",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 3900,
      "centroid": { "latitude": 34.776276, "longitude": 47.599926 },
      "id": 855,
      "name": "سنقر",
      "slug": "sonqor",
      "new": false,
      "parent": 905,
      "neighbors": [],
      "second_slug": "sonqor",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 10000,
      "centroid": { "latitude": 35.294468, "longitude": 47.00832 },
      "id": 28,
      "name": "سنندج",
      "slug": "sanandaj",
      "new": false,
      "parent": 885,
      "neighbors": [],
      "second_slug": "sanandaj",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 2420,
      "centroid": { "latitude": 31.556074, "longitude": 48.18439 },
      "id": 756,
      "name": "سوسنگرد",
      "slug": "susangerd",
      "new": true,
      "parent": 902,
      "neighbors": [],
      "second_slug": "susangerd",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 5800,
      "centroid": { "latitude": 37.943188, "longitude": 46.13413 },
      "id": 761,
      "name": "سهند",
      "slug": "sahand",
      "new": false,
      "parent": 891,
      "neighbors": [],
      "second_slug": "sahand",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 3300,
      "centroid": { "latitude": 37.15278, "longitude": 49.876785 },
      "id": 861,
      "name": "سیاهکل",
      "slug": "siahkal",
      "new": false,
      "parent": 889,
      "neighbors": [],
      "second_slug": "siahkal",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 12000,
      "centroid": { "latitude": 29.481913, "longitude": 55.669006 },
      "id": 818,
      "name": "سیرجان",
      "slug": "sirjan",
      "new": false,
      "parent": 877,
      "neighbors": [],
      "second_slug": "sirjan",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 912,
      "centroid": { "latitude": 35.57231, "longitude": 51.087868 },
      "id": 1713,
      "name": "شاهدشهر",
      "slug": "shahedshahr",
      "new": false,
      "parent": 904,
      "neighbors": [],
      "second_slug": "shahedshahr",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 15000,
      "centroid": { "latitude": 36.412704, "longitude": 55.005184 },
      "id": 707,
      "name": "شاهرود",
      "slug": "shahrud",
      "new": false,
      "parent": 882,
      "neighbors": [],
      "second_slug": "shahroud",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 3000,
      "centroid": { "latitude": 36.678875, "longitude": 46.567307 },
      "id": 858,
      "name": "شاهین دژ",
      "slug": "shahin-dej",
      "new": false,
      "parent": 881,
      "neighbors": [],
      "second_slug": "shahin-dej",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 4289,
      "centroid": { "latitude": 36.016388, "longitude": 51.48209 },
      "id": 1717,
      "name": "شمشک",
      "slug": "shemshak",
      "new": false,
      "parent": 904,
      "neighbors": [],
      "second_slug": "shemshak",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 3010,
      "centroid": { "latitude": 32.194553, "longitude": 48.258675 },
      "id": 754,
      "name": "شوش",
      "slug": "shush",
      "new": true,
      "parent": 902,
      "neighbors": [],
      "second_slug": "shush",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 6000,
      "centroid": { "latitude": 32.046917, "longitude": 48.83769 },
      "id": 602,
      "name": "شوشتر",
      "slug": "shushtar",
      "new": false,
      "parent": 902,
      "neighbors": [],
      "second_slug": "shooshtar",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 7000,
      "centroid": { "latitude": 32.33338, "longitude": 50.871063 },
      "id": 36,
      "name": "شهرکرد",
      "slug": "shahrekord",
      "new": false,
      "parent": 903,
      "neighbors": [],
      "second_slug": "shahrekord",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 15000,
      "centroid": { "latitude": 29.639816, "longitude": 52.5119 },
      "id": 6,
      "name": "شیراز",
      "slug": "shiraz",
      "new": false,
      "parent": 898,
      "neighbors": [],
      "second_slug": "shiraz",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 3450,
      "centroid": { "latitude": 37.406025, "longitude": 57.932575 },
      "id": 795,
      "name": "شیروان",
      "slug": "shirvan",
      "new": false,
      "parent": 896,
      "neighbors": [],
      "second_slug": "shirvan",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 4975,
      "centroid": { "latitude": 35.58619, "longitude": 51.11577 },
      "id": 1712,
      "name": "صباشهر",
      "slug": "sabashahr",
      "new": false,
      "parent": 904,
      "neighbors": [],
      "second_slug": "sabashahr",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 8850,
      "centroid": { "latitude": 29.79413, "longitude": 52.499115 },
      "id": 810,
      "name": "صدرا-فارس",
      "slug": "sadra",
      "new": false,
      "parent": 898,
      "neighbors": [],
      "second_slug": "sadra",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 1941,
      "centroid": { "latitude": 35.678078, "longitude": 50.818195 },
      "id": 1710,
      "name": "صفادشت",
      "slug": "safadasht-industrial-city",
      "new": false,
      "parent": 904,
      "neighbors": [],
      "second_slug": "safadasht-industrial-city",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 2100,
      "centroid": { "latitude": 37.304672, "longitude": 49.318516 },
      "id": 827,
      "name": "صومعه‌سرا",
      "slug": "someh-sara",
      "new": false,
      "parent": 889,
      "neighbors": [],
      "second_slug": "someh-sara",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 33735,
      "centroid": { "latitude": 36.19529, "longitude": 50.68096 },
      "id": 850,
      "name": "طالقان",
      "slug": "taleqan",
      "new": false,
      "parent": 895,
      "neighbors": [],
      "second_slug": "taleqan",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 5570,
      "centroid": { "latitude": 33.609398, "longitude": 56.939278 },
      "id": 788,
      "name": "طبس",
      "slug": "tabas",
      "new": false,
      "parent": 876,
      "neighbors": [],
      "second_slug": "tabas",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 3360,
      "centroid": { "latitude": 36.72293, "longitude": 51.10717 },
      "id": 1697,
      "name": "عباس‌آباد",
      "slug": "abbasabad-mazandaran",
      "new": false,
      "parent": 893,
      "neighbors": [],
      "second_slug": "abbasabad-mazandaran",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 2930,
      "centroid": { "latitude": 36.903435, "longitude": 54.856083 },
      "id": 823,
      "name": "علی‌آباد کتول",
      "slug": "aliabad-katul",
      "new": false,
      "parent": 897,
      "neighbors": [],
      "second_slug": "aliabad-katul",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 4310,
      "centroid": { "latitude": 32.270927, "longitude": 50.97159 },
      "id": 786,
      "name": "فرخ‌شهر",
      "slug": "farrokhshahr",
      "new": false,
      "parent": 903,
      "neighbors": [],
      "second_slug": "farrokhshahr",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 3120,
      "centroid": { "latitude": 34.019, "longitude": 58.172134 },
      "id": 789,
      "name": "فردوس",
      "slug": "ferdows",
      "new": false,
      "parent": 876,
      "neighbors": [],
      "second_slug": "ferdows",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 3654,
      "centroid": { "latitude": 35.597927, "longitude": 51.05822 },
      "id": 1716,
      "name": "فردوسیه",
      "slug": "ferdosiye",
      "new": false,
      "parent": 904,
      "neighbors": [],
      "second_slug": "ferdosiye",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 3440,
      "centroid": { "latitude": 36.683365, "longitude": 52.527218 },
      "id": 836,
      "name": "فریدون‌کنار",
      "slug": "fereydunkenar",
      "new": false,
      "parent": 893,
      "neighbors": [],
      "second_slug": "fereydunkenar",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 1945,
      "centroid": { "latitude": 32.554752, "longitude": 51.50685 },
      "id": 849,
      "name": "فلاورجان",
      "slug": "falavarjan",
      "new": false,
      "parent": 890,
      "neighbors": [],
      "second_slug": "falavarjan",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 2750,
      "centroid": { "latitude": 37.227806, "longitude": 49.31341 },
      "id": 860,
      "name": "فومن",
      "slug": "fuman",
      "new": false,
      "parent": 889,
      "neighbors": [],
      "second_slug": "fuman",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 3629,
      "centroid": { "latitude": 28.846992, "longitude": 52.573185 },
      "id": 1734,
      "name": "فیروزآباد",
      "slug": "firuzabad",
      "new": false,
      "parent": 898,
      "neighbors": [],
      "second_slug": "firuzabad",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 6000,
      "centroid": { "latitude": 36.464767, "longitude": 52.861168 },
      "id": 665,
      "name": "قائم‌شهر",
      "slug": "qaem-shahr",
      "new": false,
      "parent": 893,
      "neighbors": [],
      "second_slug": "qaemshahr",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 2320,
      "centroid": { "latitude": 34.36534, "longitude": 59.870625 },
      "id": 1733,
      "name": "قاسم‌آباد (خواف)",
      "slug": "qasemabad-khaf",
      "new": false,
      "parent": 880,
      "neighbors": [],
      "second_slug": "qasemabad-khaf",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 5700,
      "centroid": { "latitude": 33.736492, "longitude": 59.18651 },
      "id": 790,
      "name": "قاين",
      "slug": "ghayen",
      "new": false,
      "parent": 876,
      "neighbors": [],
      "second_slug": "ghayen",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 2800,
      "centroid": { "latitude": 35.165947, "longitude": 47.80515 },
      "id": 813,
      "name": "قروه",
      "slug": "qorveh",
      "new": false,
      "parent": 885,
      "neighbors": [],
      "second_slug": "qorveh",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 10000,
      "centroid": { "latitude": 36.275105, "longitude": 50.009815 },
      "id": 19,
      "name": "قزوین",
      "slug": "qazvin",
      "new": false,
      "parent": 878,
      "neighbors": [],
      "second_slug": "qazvin",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 60000,
      "centroid": { "latitude": 26.784285, "longitude": 55.81223 },
      "id": 660,
      "name": "قشم",
      "slug": "qeshm",
      "new": false,
      "parent": 894,
      "neighbors": [],
      "second_slug": "qeshm",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 15000,
      "centroid": { "latitude": 34.620422, "longitude": 50.853737 },
      "id": 8,
      "name": "قم",
      "slug": "qom",
      "new": false,
      "parent": 892,
      "neighbors": [],
      "second_slug": "qom",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 2930,
      "centroid": { "latitude": 36.12102, "longitude": 48.59033 },
      "id": 804,
      "name": "قیدار",
      "slug": "qeydar",
      "new": false,
      "parent": 879,
      "neighbors": [],
      "second_slug": "qeydar",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 5000,
      "centroid": { "latitude": 33.985386, "longitude": 51.406944 },
      "id": 30,
      "name": "کاشان",
      "slug": "kashan",
      "new": false,
      "parent": 890,
      "neighbors": [],
      "second_slug": "kashan",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 25000,
      "centroid": { "latitude": 35.816933, "longitude": 50.95845 },
      "id": 2,
      "name": "کرج",
      "slug": "karaj",
      "new": false,
      "parent": 895,
      "neighbors": [],
      "second_slug": "karaj",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 2130,
      "centroid": { "latitude": 36.79084, "longitude": 54.110027 },
      "id": 750,
      "name": "کردکوی",
      "slug": "Kordkuy",
      "new": true,
      "parent": 897,
      "neighbors": [],
      "second_slug": "kordkuy",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 15000,
      "centroid": { "latitude": 30.27619, "longitude": 57.05553 },
      "id": 13,
      "name": "کرمان",
      "slug": "kerman",
      "new": false,
      "parent": 877,
      "neighbors": [],
      "second_slug": "kerman",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 15000,
      "centroid": { "latitude": 34.336857, "longitude": 47.09223 },
      "id": 9,
      "name": "کرمانشاه",
      "slug": "kermanshah",
      "new": false,
      "parent": 905,
      "neighbors": [],
      "second_slug": "kermanshah",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 2530,
      "centroid": { "latitude": 37.07608, "longitude": 50.397694 },
      "id": 863,
      "name": "کلاچای",
      "slug": "kelachay",
      "new": false,
      "parent": 889,
      "neighbors": [],
      "second_slug": "kelachay",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 2003,
      "centroid": { "latitude": 36.68756, "longitude": 51.24713 },
      "id": 1695,
      "name": "کلارآباد",
      "slug": "kelarabad",
      "new": false,
      "parent": 893,
      "neighbors": [],
      "second_slug": "kelarabad",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 6009,
      "centroid": { "latitude": 36.49605, "longitude": 51.153343 },
      "id": 1696,
      "name": "کلاردشت",
      "slug": "kelarestan",
      "new": false,
      "parent": 893,
      "neighbors": [],
      "second_slug": "kelarestan",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 2690,
      "centroid": { "latitude": 37.37935, "longitude": 55.49292 },
      "id": 1692,
      "name": "کلاله",
      "slug": "kalale",
      "new": false,
      "parent": 897,
      "neighbors": [],
      "second_slug": "kalale",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 3000,
      "centroid": { "latitude": 34.503487, "longitude": 47.958588 },
      "id": 821,
      "name": "کنگاور",
      "slug": "kangavar",
      "new": false,
      "parent": 905,
      "neighbors": [],
      "second_slug": "kangavar",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 2400,
      "centroid": { "latitude": 33.530502, "longitude": 47.609985 },
      "id": 831,
      "name": "کوهدشت",
      "slug": "kuhdasht",
      "new": false,
      "parent": 884,
      "neighbors": [],
      "second_slug": "kuhdasht",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 1714,
      "centroid": { "latitude": 35.96017, "longitude": 50.792908 },
      "id": 1738,
      "name": "کوهسار",
      "slug": "koohsar",
      "new": false,
      "parent": 895,
      "neighbors": [],
      "second_slug": "koohsar",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 2286,
      "centroid": { "latitude": 35.517925, "longitude": 51.360626 },
      "id": 1708,
      "name": "کهریزک",
      "slug": "kahrizak",
      "new": false,
      "parent": 904,
      "neighbors": [],
      "second_slug": "kahrizak",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 2158,
      "centroid": { "latitude": 37.416744, "longitude": 49.894234 },
      "id": 1687,
      "name": "کیاشهر",
      "slug": "kiashahr",
      "new": false,
      "parent": 889,
      "neighbors": [],
      "second_slug": "kiashahr",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 5000,
      "centroid": { "latitude": 26.534016, "longitude": 53.974907 },
      "id": 33,
      "name": "کیش",
      "slug": "kish",
      "new": false,
      "parent": 894,
      "neighbors": [],
      "second_slug": "kish",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 6528,
      "centroid": { "latitude": 35.55402, "longitude": 52.153812 },
      "id": 1719,
      "name": "کیلان",
      "slug": "kilan",
      "new": false,
      "parent": 904,
      "neighbors": [],
      "second_slug": "kilan",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 8000,
      "centroid": { "latitude": 36.855213, "longitude": 54.452137 },
      "id": 21,
      "name": "گرگان",
      "slug": "gorgan",
      "new": false,
      "parent": 897,
      "neighbors": [],
      "second_slug": "gorgan",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 3427,
      "centroid": { "latitude": 35.75384, "longitude": 51.06327 },
      "id": 1720,
      "name": "گرمدره",
      "slug": "garmdareh",
      "new": false,
      "parent": 895,
      "neighbors": [],
      "second_slug": "garmdareh",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 4770,
      "centroid": { "latitude": 35.20643, "longitude": 52.336246 },
      "id": 806,
      "name": "گرمسار",
      "slug": "garmsar",
      "new": false,
      "parent": 882,
      "neighbors": [],
      "second_slug": "garmsar",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 3800,
      "centroid": { "latitude": 33.456615, "longitude": 50.276993 },
      "id": 848,
      "name": "گلپایگان",
      "slug": "golpayegan",
      "new": false,
      "parent": 890,
      "neighbors": [],
      "second_slug": "golpayegan",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 2968,
      "centroid": { "latitude": 35.51121, "longitude": 51.169884 },
      "id": 1706,
      "name": "گلستان",
      "slug": "golestan-baharestan",
      "new": false,
      "parent": 904,
      "neighbors": [],
      "second_slug": "golestan-baharestan",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 1300,
      "centroid": { "latitude": 37.07294, "longitude": 54.073483 },
      "id": 749,
      "name": "گمیشان",
      "slug": "gomishan",
      "new": true,
      "parent": 897,
      "neighbors": [],
      "second_slug": "gomishan",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 5230,
      "centroid": { "latitude": 34.350037, "longitude": 58.694553 },
      "id": 847,
      "name": "گناباد",
      "slug": "gonabad",
      "new": false,
      "parent": 880,
      "neighbors": [],
      "second_slug": "gonabad",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 5500,
      "centroid": { "latitude": 37.24207, "longitude": 55.181618 },
      "id": 743,
      "name": "گنبد کاووس",
      "slug": "gonbad-kavus",
      "new": true,
      "parent": 897,
      "neighbors": [],
      "second_slug": "gonbad-kavus",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 11026,
      "centroid": { "latitude": 27.664463, "longitude": 54.32605 },
      "id": 1730,
      "name": "لار",
      "slug": "lar",
      "new": false,
      "parent": 898,
      "neighbors": [],
      "second_slug": "lar",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 6602,
      "centroid": { "latitude": 27.340551, "longitude": 53.18399 },
      "id": 1731,
      "name": "لامرد",
      "slug": "lamerd",
      "new": false,
      "parent": 898,
      "neighbors": [],
      "second_slug": "lamerd",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 4360,
      "centroid": { "latitude": 37.205982, "longitude": 50.00578 },
      "id": 746,
      "name": "لاهیجان",
      "slug": "lahijan",
      "new": true,
      "parent": 889,
      "neighbors": [],
      "second_slug": "lahijan",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 4100,
      "centroid": { "latitude": 31.517256, "longitude": 50.82154 },
      "id": 787,
      "name": "لردگان",
      "slug": "lordegan",
      "new": false,
      "parent": 903,
      "neighbors": [],
      "second_slug": "lordegan",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 1,
      "centroid": { "latitude": 37.35891, "longitude": 49.86295 },
      "id": 1690,
      "name": "لشت نشا",
      "slug": "lashtenesha",
      "new": false,
      "parent": 889,
      "neighbors": [],
      "second_slug": "lashtenesha",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 3000,
      "centroid": { "latitude": 37.19115, "longitude": 50.155136 },
      "id": 828,
      "name": "لنگرود",
      "slug": "langarud",
      "new": false,
      "parent": 889,
      "neighbors": [],
      "second_slug": "langarud",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 5900,
      "centroid": { "latitude": 37.380363, "longitude": 49.146854 },
      "id": 862,
      "name": "ماسال",
      "slug": "masal",
      "new": false,
      "parent": 889,
      "neighbors": [],
      "second_slug": "masal",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 6270,
      "centroid": { "latitude": 39.29131, "longitude": 44.489895 },
      "id": 856,
      "name": "ماکو",
      "slug": "maku",
      "new": false,
      "parent": 881,
      "neighbors": [],
      "second_slug": "maku",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 3500,
      "centroid": { "latitude": 33.905087, "longitude": 50.458633 },
      "id": 840,
      "name": "محلات",
      "slug": "mahalat",
      "new": false,
      "parent": 901,
      "neighbors": [],
      "second_slug": "mahalat",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 2060,
      "centroid": { "latitude": 36.221375, "longitude": 50.18347 },
      "id": 873,
      "name": "محمدیه-قزوین",
      "slug": "mohammadieh",
      "new": false,
      "parent": 878,
      "neighbors": [],
      "second_slug": "mohammadiyeh",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 3200,
      "centroid": { "latitude": 36.628536, "longitude": 52.262524 },
      "id": 837,
      "name": "محمودآباد",
      "slug": "mahmudabad",
      "new": false,
      "parent": 893,
      "neighbors": [],
      "second_slug": "mahmudabad",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 9760,
      "centroid": { "latitude": 37.380684, "longitude": 46.236366 },
      "id": 762,
      "name": "مراغه",
      "slug": "maragheh",
      "new": false,
      "parent": 891,
      "neighbors": [],
      "second_slug": "maragheh",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 4250,
      "centroid": { "latitude": 38.43119, "longitude": 45.766144 },
      "id": 763,
      "name": "مرند",
      "slug": "marand",
      "new": false,
      "parent": 891,
      "neighbors": [],
      "second_slug": "marand",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 2870,
      "centroid": { "latitude": 35.519108, "longitude": 46.180264 },
      "id": 814,
      "name": "مریوان",
      "slug": "marivan",
      "new": false,
      "parent": 885,
      "neighbors": [],
      "second_slug": "marivan",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 6000,
      "centroid": { "latitude": 31.957708, "longitude": 49.287884 },
      "id": 317,
      "name": "مسجد سلیمان",
      "slug": "masjed-e-soleyman",
      "new": false,
      "parent": 902,
      "neighbors": [],
      "second_slug": "masjed-soleyman",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 4500,
      "centroid": { "latitude": 38.3873, "longitude": 47.674034 },
      "id": 773,
      "name": "مشکین‌شهر",
      "slug": "meshgin-shahr",
      "new": false,
      "parent": 906,
      "neighbors": [],
      "second_slug": "meshgin-shahr",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 20000,
      "centroid": { "latitude": 36.304897, "longitude": 59.577873 },
      "id": 3,
      "name": "مشهد",
      "slug": "mashhad",
      "new": false,
      "parent": 880,
      "neighbors": [],
      "second_slug": "mashhad",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 4400,
      "centroid": { "latitude": 34.302536, "longitude": 48.81713 },
      "id": 843,
      "name": "ملایر",
      "slug": "malayer",
      "new": false,
      "parent": 899,
      "neighbors": [],
      "second_slug": "malayer",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 5000,
      "centroid": { "latitude": 36.76707, "longitude": 45.728313 },
      "id": 769,
      "name": "مهاباد",
      "slug": "mahabad",
      "new": false,
      "parent": 881,
      "neighbors": [],
      "second_slug": "mahabad",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 4250,
      "centroid": { "latitude": 36.967766, "longitude": 46.1089 },
      "id": 792,
      "name": "میاندوآب",
      "slug": "miandoab",
      "new": false,
      "parent": 881,
      "neighbors": [],
      "second_slug": "miandoab",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 4700,
      "centroid": { "latitude": 37.42485, "longitude": 47.72236 },
      "id": 764,
      "name": "میانه",
      "slug": "mianeh",
      "new": false,
      "parent": 891,
      "neighbors": [],
      "second_slug": "mianeh",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 15300,
      "centroid": { "latitude": 32.21285, "longitude": 54.032684 },
      "id": 845,
      "name": "میبد",
      "slug": "meybod",
      "new": false,
      "parent": 886,
      "neighbors": [],
      "second_slug": "meybod",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 7100,
      "centroid": { "latitude": 27.131184, "longitude": 57.076424 },
      "id": 841,
      "name": "میناب",
      "slug": "minab",
      "new": false,
      "parent": 894,
      "neighbors": [],
      "second_slug": "minab",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 1657,
      "centroid": { "latitude": 37.22931, "longitude": 55.379745 },
      "id": 1693,
      "name": "مینودشت",
      "slug": "minoodasht",
      "new": false,
      "parent": 897,
      "neighbors": [],
      "second_slug": "minoodasht",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 10000,
      "centroid": { "latitude": 32.63863, "longitude": 51.36768 },
      "id": 31,
      "name": "نجف‌آباد",
      "slug": "najafabad",
      "new": false,
      "parent": 890,
      "neighbors": [],
      "second_slug": "najafabad",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 1950,
      "centroid": { "latitude": 35.562557, "longitude": 51.16034 },
      "id": 784,
      "name": "نسیم‌شهر",
      "slug": "nasimshahr",
      "new": false,
      "parent": 904,
      "neighbors": [],
      "second_slug": "nasimshahr",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 4080,
      "centroid": { "latitude": 35.95977, "longitude": 50.605278 },
      "id": 774,
      "name": "نظرآباد",
      "slug": "nazarabad",
      "new": false,
      "parent": 895,
      "neighbors": [],
      "second_slug": "nazarabad",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 3030,
      "centroid": { "latitude": 36.95819, "longitude": 45.389862 },
      "id": 770,
      "name": "نقده",
      "slug": "naqadeh",
      "new": false,
      "parent": 881,
      "neighbors": [],
      "second_slug": "naqadeh",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 4000,
      "centroid": { "latitude": 36.64784, "longitude": 53.29312 },
      "id": 838,
      "name": "نکا",
      "slug": "neka",
      "new": false,
      "parent": 893,
      "neighbors": [],
      "second_slug": "neka",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 3230,
      "centroid": { "latitude": 36.57329, "longitude": 52.02422 },
      "id": 744,
      "name": "نور",
      "slug": "nur",
      "new": true,
      "parent": 893,
      "neighbors": [],
      "second_slug": "nur",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 2790,
      "centroid": { "latitude": 34.0679, "longitude": 47.97227 },
      "id": 753,
      "name": "نورآباد",
      "slug": "nurabad",
      "new": true,
      "parent": 884,
      "neighbors": [],
      "second_slug": "nurabad",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 15000,
      "centroid": { "latitude": 36.64976, "longitude": 51.490864 },
      "id": 709,
      "name": "نوشهر",
      "slug": "nowshahr",
      "new": false,
      "parent": 893,
      "neighbors": [],
      "second_slug": "nowshahr",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 3800,
      "centroid": { "latitude": 34.194206, "longitude": 48.373367 },
      "id": 844,
      "name": "نهاوند",
      "slug": "nahavand",
      "new": false,
      "parent": 899,
      "neighbors": [],
      "second_slug": "nahavand",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 4891,
      "centroid": { "latitude": 29.192411, "longitude": 54.319893 },
      "id": 1726,
      "name": "نی‌ریز",
      "slug": "neyriz",
      "new": false,
      "parent": 898,
      "neighbors": [],
      "second_slug": "neyriz",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 8000,
      "centroid": { "latitude": 36.22882, "longitude": 58.79653 },
      "id": 318,
      "name": "نیشابور",
      "slug": "neyshabur",
      "new": false,
      "parent": 880,
      "neighbors": [],
      "second_slug": "neyshabur",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 1263,
      "centroid": { "latitude": 35.607914, "longitude": 51.031406 },
      "id": 1711,
      "name": "وحیدیه",
      "slug": "vahidieh",
      "new": false,
      "parent": 904,
      "neighbors": [],
      "second_slug": "vahidieh",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 15000,
      "centroid": { "latitude": 34.810787, "longitude": 48.52082 },
      "id": 14,
      "name": "همدان",
      "slug": "hamedan",
      "new": false,
      "parent": 899,
      "neighbors": [],
      "second_slug": "hamedan",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 7000,
      "centroid": { "latitude": 30.680979, "longitude": 51.564827 },
      "id": 38,
      "name": "یاسوج",
      "slug": "yasuj",
      "new": false,
      "parent": 887,
      "neighbors": [],
      "second_slug": "yasuj",
      "tags": []
    },
    {
      "level": "place2",
      "radius": 15000,
      "centroid": { "latitude": 31.88442, "longitude": 54.342766 },
      "id": 16,
      "name": "یزد",
      "slug": "yazd",
      "new": false,
      "parent": 886,
      "neighbors": [],
      "second_slug": "yazd",
      "tags": []
    }
  ],
  "top_cities": [
    "tehran",
    "mashhad",
    "karaj",
    "shiraz",
    "isfahan",
    "ahvaz",
    "tabriz",
    "kermanshah",
    "qom",
    "rasht"
  ]
}
export default cities
